export const TRENDING_MOVIES = 'TRENDING_MOVIES'

export const LOGIN = 'LOGIN_AUTH'
export const USER_INFO = 'USER_INFO'
export const GET_ALL_DOCTORS = 'GET_ALL_DOCTORS'
export const GET_ALL_APPOINTMENTS = 'GET_ALL_APPOINTMENTS'
