export const LOGIN = 'login'
export const USER_INFO = 'user_info'
export const TRENDING_MOVIES = 'trending_movies'
export const ALL_DOCTORS = 'all_doctors'
export const ALL_APPOINTMENTS = 'all_appointments'
